### ISSUE TITLE
Unable to compare union type (Float? | Integer?)

### ISSUE THREAD

**Issue by steowens** [ceylon/ceylon.language#796] opened 2015-12-28 16:21 UTC
So far I can find no way to build a compare function which accepts a class which has a value of type (Float? | Integer?).

For example:

```
shared default actual Comparison compare(Number other){
        if(!(other.val exists)&&!(val exists)){
            return equal;
        } else if(val exists && !(other.val exists)){
            return larger;
        } else if(!(val exists) && other.val exists){
            return smaller;
        } else {
           if(val is Float){
               if(other.val is Float){
                  // Generates compiler error
                  // Specified expression must be assignable to declared type of ov:
                  //        Integer?|Float? (Null|Integer|Float) is not assignable to Float
                   Float ov = other.val;
                  
                  // Generates compiler error
                  // Incorrect syntax: missing statement-ending ; at other expecting statement-ending ;
                  Float ov2 = (Float) other.val;
                 
                   // Generates compiler error
                  // Operand expressions must be comparable: 
                  //   Integer?|Float? (Null|Integer|Float) is not a subtype of Comparable 
                  return val <=> other.val;
               }
           }
            
        }
        
    }
```
Even though the above code tests the type of val and other.val and asserts them to be the same, it is impossible ot cast or compare the two values.

**Comment by thradec** [comment] 2015-12-28 16:31
Did you try type narrowing? In your example ...

```
if( is Float f = val, is Float f2 = other.val ) {
    return f <=> f2;
}
```

**Comment by gavinking** [comment] 2015-12-29 13:12
Hi, @steowens, the syntax `other.val is Float` does *not* perform type narrowing, it is just a plain expression of type `Boolean`. What you would need is an `is` _condition_, as shown above by @thradec.

Also the syntax `(Float) other.val` is simply not legal Ceylon. That is a Java/C typecast, which does not exist in Ceylon.

You can find more information about this syntax [here](http://ceylon-lang.org/documentation/1.2/tour/attributes-control-structures/#condition_lists), [here](http://ceylon-lang.org/documentation/1.2/reference/statement/conditions/), and [here](http://ceylon-lang.org/documentation/current/spec/html_single/index.html#controlstructureconditions).

I'm closing this issue since it's not a bug in Ceylon.

**Closed by gavinking** 2015-12-29 13:12 UTC

**Comment by steowens** [comment] 2016-01-16 03:07
Thank you.  Just saw your question and response.  I am unfamiliar with Ceylon and was evaluating the language.

**Comment by DiegoCoronel** [comment] 2016-01-16 13:49
@steowens you can try both:
- https://gitter.im/ceylon/user
- https://groups.google.com/forum/#!forum/ceylon-users

I believe those are enough to start.. but theres also _dev_ chat and forum

**Comment by steowens** [comment] 2016-01-17 10:47
Thank you.  I didn't see those mentioned in your README.md file.  It might be a nice bit of info to include.
