### ISSUE TITLE
dupe result in Class.declaredMemberDeclarations()

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#617] opened 2015-01-16 00:36 UTC
Given:

```ceylon
class Greet(shared String hello) {}
shared void run() =>
    print(`class Greet`.declaredMemberDeclarations<NestableDeclaration>());
```

I get:

    [value p::Greet.hello, value p::Greet.hello]

**Comment by lucaswerkmeister** [comment] 2015-02-18 21:30
Dupe of #566?

**Comment by tombentley** [comment] 2015-03-16 14:58
Yes, dupe. Closing.

**Closed by tombentley** 2015-03-16 14:58 UTC
Labels: BUG, Duplicate, JVM runtime
