### ISSUE TITLE
Missing annotation metadata for String,Float,Integer on JVM

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#690] opened 2015-05-26 02:27 UTC
print(`class String`.annotations<Annotation>());

result in `[]`. Same for `Integer` and `Float`.

**Comment by gavinking** [comment] 2015-05-26 06:44
This is basically a dupe of #408, isn't it?

**Comment by tombentley** [comment] 2015-05-26 06:45
Yes, it's a dupe.

**Closed** 2015-05-26 06:45 UTC
Labels: BUG, Duplicate
