### ISSUE TITLE
Duplicates in declaredMemberDeclarations

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon.language#622] opened 2015-02-03 17:27 UTC
Initializer parameters are returned twice when querying declared value members:

````ceylon
class Prueba(String s) {
  shared String a = s;
  shared String b => s;
}

`class Prueba`.declaredMemberDeclarations<ValueDeclaration>()
````
prints `[value Prueba.s, value Prueba.a, value Prueba.b, value Prueba.s]`

**Comment by lucaswerkmeister** [comment] 2015-02-18 21:29
Dupe of #617 and #566?

**Comment by tombentley** [comment] 2015-03-16 14:56
Yes, dupe. Closing.

**Closed by tombentley** 2015-03-16 14:56 UTC
Labels: BUG, JVM runtime, Metamodel
